---
driver:
  name: dokken
  privileged: true
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>
  chef_license: accept-silent
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup:ro

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true
  chef_license: accept-silent
  enforce_idempotency: true
  multiple_converge: 2
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-22.04
    driver:
      image: dokken/ubuntu-22.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl systemd

  - name: ubuntu-24.04
    driver:
      image: dokken/ubuntu-24.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl systemd

  - name: debian-12
    driver:
      image: dokken/debian-12
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y curl systemd

  - name: centos-stream-9
    driver:
      image: dokken/centos-stream-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl systemd

  - name: rockylinux-9
    driver:
      image: dokken/rockylinux-9
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl systemd

  - name: amazon-2023
    driver:
      image: dokken/amazonlinux-2023
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install sudo curl systemd

suites:
  - name: default
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      httpd:
        default_vhost:
          enabled: true

  - name: ssl
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/ssl
    attributes:
      httpd:
        ssl:
          enabled: true
          certificate: /etc/pki/tls/certs/localhost.crt
          certificate_key: /etc/pki/tls/private/localhost.key
        default_vhost:
          enabled: true

  - name: source
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/source
    attributes:
      httpd:
        install_method: source
        version: 2.4.57
        mpm: event
        default_vhost:
          enabled: true

  - name: prefork-mpm
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/prefork-mpm
    attributes:
      httpd:
        mpm: prefork
        default_vhost:
          enabled: true

  - name: multi-vhost
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/multi-vhost
    attributes:
      httpd:
        default_vhost:
          enabled: true
        vhosts:
          example:
            domain: example.com
            document_root: /var/www/example
            port: 8080
          secure:
            domain: secure.example.com
            document_root: /var/www/secure
            ssl_enabled: true
            ssl_cert: /etc/pki/tls/certs/localhost.crt
            ssl_key: /etc/pki/tls/private/localhost.key

  - name: modules
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/modules
    attributes:
      httpd:
        default_vhost:
          enabled: true
        modules:
          - proxy
          - proxy_http
          - rewrite
        extra_modules:
          - proxy_balancer
          - lbmethod_byrequests

  - name: performance-tuning
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/performance-tuning
    attributes:
      httpd:
        default_vhost:
          enabled: true
        performance:
          max_request_workers: 400
          threads_per_child: 25
          max_connections_per_child: 10000
          server_limit: 16
          thread_limit: 64

  - name: telemetry
    run_list:
      - recipe[httpd::default]
    verifier:
      inspec_tests:
        - test/integration/telemetry
    attributes:
      httpd:
        default_vhost:
          enabled: true
        telemetry:
          enabled: true
          prometheus:
            scrape_uri: "/server-status?auto"
            telemetry_path: "/metrics"
            metrics:
              - connections
              - scoreboard
              - cpu
              - requests
              - throughput
              - response_time
              - workers